name: Node CI

on:
  pull_request:
    branches: [source]

jobs:
  pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install
        run: yarn --frozen-lockfile
      - name: test
        run: yarn test
      - name: build
        run: yarn build
