name: Node CI

on:
  pull_request:
    branches: [ source ]


jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }} 
      - run: yarn --frozen-lockfile
      - run: yarn test
      - run: yarn build
