name: Node CI

on:
  pull_request:
    branches: [source]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: yarn install, build, and test
        run: |
          yarn --frozen-lockfile
          yarn test
          yarn build
